// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hstepvryfsdyvowfzesd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzdGVwdnJ5ZnNkeXZvd2Z6ZXNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY0MjE5NjYsImV4cCI6MjA5MTk5Nzk2Nn0.7IZAUZ43mZCL10CjDTjSXoCG8HSqM87GoApqrND-Syw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});